"""
An implementation of the Gram Schmidt Orthogonalization process.

INPUTS:
    -- basis : list[vector] all must be same dimension
OUTPUT:
    -- orthogonal_basis: list[vector]
"""


# This file was *autogenerated* from the file gram_schmidt.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
def gram_schmidt(basis):
    # STEP 0: Verify wheter they are all the same dimension
    assert len(basis) > _sage_const_0 
    dim = len(basis[_sage_const_0 ])
    assert all(len(v) == dim for v in basis)

    orthogonal_basis = []
    # Step 1
    orthogonal_basis.append(basis[_sage_const_0 ])

    # Step 2
    for i in range(_sage_const_1 , len(basis)):
        # Find \Sigma_{j = 1}^{i -1}((b_i \dot b_j*)/(b_j* \dot b_j*)) * b_j*
        orthogonal_projection = vector([_sage_const_0  for k in range(dim)])
        for j in range(_sage_const_0 , i):
            orthogonal_projection += (basis[i].dot_product(basis[j]) / basis[j].dot_product(basis[j]) ) * basis[j]

        # Find b_i^*
        orthogonal_basis.append(basis[i] - orthogonal_projection)

    return orthogonal_basis
        

