

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_15 = Integer(15); _sage_const_23 = Integer(23); _sage_const_11 = Integer(11); _sage_const_46 = Integer(46); _sage_const_3 = Integer(3); _sage_const_32 = Integer(32)
from LLL import LLL

# print(gram_schmidt([vector([-2, 2]), vector([-2, 1])]))
print(LLL([vector([-_sage_const_2 , _sage_const_2 ]), vector([-_sage_const_2 , _sage_const_1 ])]))
print(LLL([vector([_sage_const_15 , _sage_const_23 , _sage_const_11 ]), vector([_sage_const_46 , _sage_const_15 , _sage_const_3 ]), vector([_sage_const_32 ,_sage_const_1 ,_sage_const_1 ])]))

